repo: 'grain-globber'

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: 'index.html'
    locked: true

css:
  - path: 'css/main.css'
    valid: true
    bestPractices: true
    has:
      - ['html', 'box-sizing', 'border-box']
      - ['*', 'box-sizing', 'inherit']
      - ['.grains']
      - ['.grains img', 'float', 'left']
      - ['.grains li']
      - ['.grains h2']
      - ['.grains p']

js:
  - path: 'js/grains.js'
    locked: true

  - path: 'js/main.js'
    valid: true
    bestPractices: true
    search:
      - '\$\('
      - 'var'
      - 'forEach'
      - 'function'
    search_not:
      - 'document.write\('
      - 'console.log\('
      - 'alert\('
      - 'prompt\('

screenshots:
  - path: 'index.html'
    sizes: [320]
